// Circuit configuration data

export interface CircuitData {
  id: string;
  name: string;
  country: string;
  length_km: number;
  corners: number;
  drs_zones: number;
  lap_record: number;
  typical_pit_loss: number;
  tire_wear: 'LOW' | 'MEDIUM' | 'HIGH';
  overtaking_difficulty: 'EASY' | 'MEDIUM' | 'HARD';
}

export const CIRCUITS: Record<string, CircuitData> = {
  'bahrain': {
    id: 'bahrain',
    name: 'Bahrain International Circuit',
    country: 'Bahrain',
    length_km: 5.412,
    corners: 15,
    drs_zones: 3,
    lap_record: 91.537,
    typical_pit_loss: 22.0,
    tire_wear: 'HIGH',
    overtaking_difficulty: 'MEDIUM',
  },
  'jeddah': {
    id: 'jeddah',
    name: 'Jeddah Corniche Circuit',
    country: 'Saudi Arabia',
    length_km: 6.174,
    corners: 27,
    drs_zones: 3,
    lap_record: 88.735,
    typical_pit_loss: 23.5,
    tire_wear: 'LOW',
    overtaking_difficulty: 'EASY',
  },
  'albert_park': {
    id: 'albert_park',
    name: 'Albert Park Circuit',
    country: 'Australia',
    length_km: 5.278,
    corners: 14,
    drs_zones: 4,
    lap_record: 78.995,
    typical_pit_loss: 21.5,
    tire_wear: 'MEDIUM',
    overtaking_difficulty: 'MEDIUM',
  },
  'imola': {
    id: 'imola',
    name: 'Autodromo Enzo e Dino Ferrari',
    country: 'Italy',
    length_km: 4.909,
    corners: 19,
    drs_zones: 2,
    lap_record: 75.484,
    typical_pit_loss: 20.0,
    tire_wear: 'MEDIUM',
    overtaking_difficulty: 'HARD',
  },
  'miami': {
    id: 'miami',
    name: 'Miami International Autodrome',
    country: 'USA',
    length_km: 5.410,
    corners: 19,
    drs_zones: 3,
    lap_record: 90.584,
    typical_pit_loss: 22.0,
    tire_wear: 'MEDIUM',
    overtaking_difficulty: 'MEDIUM',
  },
  'monaco': {
    id: 'monaco',
    name: 'Circuit de Monaco',
    country: 'Monaco',
    length_km: 3.337,
    corners: 19,
    drs_zones: 1,
    lap_record: 70.246,
    typical_pit_loss: 16.0,
    tire_wear: 'LOW',
    overtaking_difficulty: 'HARD',
  },
  'barcelona': {
    id: 'barcelona',
    name: 'Circuit de Barcelona-Catalunya',
    country: 'Spain',
    length_km: 4.675,
    corners: 16,
    drs_zones: 2,
    lap_record: 78.149,
    typical_pit_loss: 19.5,
    tire_wear: 'HIGH',
    overtaking_difficulty: 'MEDIUM',
  },
  'montreal': {
    id: 'montreal',
    name: 'Circuit Gilles Villeneuve',
    country: 'Canada',
    length_km: 4.361,
    corners: 14,
    drs_zones: 3,
    lap_record: 72.330,
    typical_pit_loss: 18.5,
    tire_wear: 'MEDIUM',
    overtaking_difficulty: 'EASY',
  },
  'red_bull_ring': {
    id: 'red_bull_ring',
    name: 'Red Bull Ring',
    country: 'Austria',
    length_km: 4.318,
    corners: 10,
    drs_zones: 3,
    lap_record: 64.984,
    typical_pit_loss: 18.0,
    tire_wear: 'MEDIUM',
    overtaking_difficulty: 'EASY',
  },
  'silverstone': {
    id: 'silverstone',
    name: 'Silverstone Circuit',
    country: 'United Kingdom',
    length_km: 5.891,
    corners: 18,
    drs_zones: 2,
    lap_record: 86.584,
    typical_pit_loss: 23.0,
    tire_wear: 'HIGH',
    overtaking_difficulty: 'MEDIUM',
  },
  'hungaroring': {
    id: 'hungaroring',
    name: 'Hungaroring',
    country: 'Hungary',
    length_km: 4.381,
    corners: 14,
    drs_zones: 2,
    lap_record: 76.627,
    typical_pit_loss: 19.0,
    tire_wear: 'HIGH',
    overtaking_difficulty: 'HARD',
  },
  'spa': {
    id: 'spa',
    name: 'Circuit de Spa-Francorchamps',
    country: 'Belgium',
    length_km: 7.004,
    corners: 19,
    drs_zones: 2,
    lap_record: 103.486,
    typical_pit_loss: 25.0,
    tire_wear: 'MEDIUM',
    overtaking_difficulty: 'EASY',
  },
  'zandvoort': {
    id: 'zandvoort',
    name: 'Circuit Zandvoort',
    country: 'Netherlands',
    length_km: 4.259,
    corners: 14,
    drs_zones: 2,
    lap_record: 70.299,
    typical_pit_loss: 18.0,
    tire_wear: 'MEDIUM',
    overtaking_difficulty: 'HARD',
  },
  'monza': {
    id: 'monza',
    name: 'Autodromo Nazionale di Monza',
    country: 'Italy',
    length_km: 5.793,
    corners: 11,
    drs_zones: 3,
    lap_record: 81.046,
    typical_pit_loss: 22.5,
    tire_wear: 'LOW',
    overtaking_difficulty: 'EASY',
  },
  'singapore': {
    id: 'singapore',
    name: 'Marina Bay Street Circuit',
    country: 'Singapore',
    length_km: 4.940,
    corners: 19,
    drs_zones: 3,
    lap_record: 91.905,
    typical_pit_loss: 20.5,
    tire_wear: 'LOW',
    overtaking_difficulty: 'MEDIUM',
  },
  'suzuka': {
    id: 'suzuka',
    name: 'Suzuka International Racing Course',
    country: 'Japan',
    length_km: 5.807,
    corners: 18,
    drs_zones: 2,
    lap_record: 87.270,
    typical_pit_loss: 22.5,
    tire_wear: 'HIGH',
    overtaking_difficulty: 'MEDIUM',
  },
  'losail': {
    id: 'losail',
    name: 'Losail International Circuit',
    country: 'Qatar',
    length_km: 5.380,
    corners: 16,
    drs_zones: 2,
    lap_record: 84.396,
    typical_pit_loss: 21.5,
    tire_wear: 'MEDIUM',
    overtaking_difficulty: 'MEDIUM',
  },
  'cota': {
    id: 'cota',
    name: 'Circuit of the Americas',
    country: 'USA',
    length_km: 5.513,
    corners: 20,
    drs_zones: 2,
    lap_record: 95.665,
    typical_pit_loss: 22.0,
    tire_wear: 'HIGH',
    overtaking_difficulty: 'MEDIUM',
  },
  'mexico': {
    id: 'mexico',
    name: 'Autódromo Hermanos Rodríguez',
    country: 'Mexico',
    length_km: 4.304,
    corners: 17,
    drs_zones: 3,
    lap_record: 76.555,
    typical_pit_loss: 18.5,
    tire_wear: 'MEDIUM',
    overtaking_difficulty: 'EASY',
  },
  'interlagos': {
    id: 'interlagos',
    name: 'Autódromo José Carlos Pace',
    country: 'Brazil',
    length_km: 4.309,
    corners: 15,
    drs_zones: 2,
    lap_record: 70.540,
    typical_pit_loss: 18.5,
    tire_wear: 'MEDIUM',
    overtaking_difficulty: 'MEDIUM',
  },
  'las_vegas': {
    id: 'las_vegas',
    name: 'Las Vegas Street Circuit',
    country: 'USA',
    length_km: 6.120,
    corners: 17,
    drs_zones: 2,
    lap_record: 96.169,
    typical_pit_loss: 23.5,
    tire_wear: 'LOW',
    overtaking_difficulty: 'EASY',
  },
  'yas_marina': {
    id: 'yas_marina',
    name: 'Yas Marina Circuit',
    country: 'UAE',
    length_km: 5.281,
    corners: 16,
    drs_zones: 2,
    lap_record: 84.358,
    typical_pit_loss: 21.5,
    tire_wear: 'LOW',
    overtaking_difficulty: 'MEDIUM',
  },
};

export const getCircuitById = (id: string): CircuitData | undefined => {
  return CIRCUITS[id];
};

export const getAllCircuits = (): CircuitData[] => {
  return Object.values(CIRCUITS);
};
